### PR TITLE
use cluster dns to reach apiserver for rustls - for #587

### LINKED ISSUE #153: rustls cannot reach a cluster through ip
```sh
kube api: ReqwestError: error sending request for url (https://192.168.64.3:8443/apis/babylontech.co.uk/v1/namespaces/apps/shipcatmanifests/dummy-s
ervice2/status?): error trying to connect: invalid dnsname: ReqwestError(reqwest::Error { kind: Request, url: "https://192.168.64.3:8443/apis/babylontech.co.uk/v1/namespaces/apps/shipcatmanifests/dummy-service2/status?", source: hyper::Error(Connect, Custom { kind: Other, error: "invalid dnsname" }) })
```

This is due to missing support for it upstream: https://github.com/ctz/hyper-rustls/issues/56

## In-cluster ~~broken~~ fixed
Cannot seem to get this to work within-cluster yet because we always get a straight IP to connect to.
At least in EKS I seem to just get a straight IP to connect to the api server. So this is pretty ununsable for me atm.

**Update**: in-cluster fixed in #597

## local minikube / k3d workaround
Add an ip entry (here `192.168.64.3 localhost`) to `/etc/hosts`, then and search replace the ip with `localhost` in `~/.kube/config`

### PR DESCRIPTION
**Pull request by clux**
~~untested~~ based on suggestion in #587 to fix #153

### CODE REVIEW

**Comment by teozkr** [comment]
FWIW, you still need to use the environment variable when implementing a custom DNS server...

**Comment by clux** [comment]
Do we? I thought that was the whole point to rely on DNS, rather than use the evars.

**Comment by clux** [comment]
This passed integration tests on k3s now.

File: kube/src/config/mod.rs [hunk 1]
```diff
@@ -91,11 +91,12 @@ impl Config {
...
-            hostenv: incluster_config::SERVICE_HOSTENV,
-            portenv: incluster_config::SERVICE_PORTENV,
-        })?;
-        let cluster_url = cluster_url.parse::<http::Uri>()?;
+        let cluster_url = incluster_config::kube_dns();
+        //let cluster_url = incluster_config::kube_server().ok_or(ConfigError::MissingInClusterVariables {
+        //    hostenv: incluster_config::SERVICE_HOSTENV,
+        //    portenv: incluster_config::SERVICE_PORTENV,
+        //})?;
+        //let cluster_url = cluster_url.parse::<http::Uri>()?;
```
Comment (clux) [inline kube/src/config/mod.rs:99]: If this is a sound method, then a question is how do we roll this out.

Evar to opt in to new dns method? I am a bit scared to jump to the dns method that client-go doesn't even use on a hard-swap.

Comment (clux) [reply kube/src/config/mod.rs]: rolling it out for rustls only (because that's broken anyway).

**Comment by teozkr** [comment]
> Do we? I thought that was the whole point to rely on DNS, rather than use the evars. Bumped PR.

Yeah, but the DNS server itself needs to have some way to reach the apiserver as well (chicken-and-egg problem :p). Not contesting that this is the correct solution for 99% of applications though.

File: kube/src/config/mod.rs [hunk 2]
```diff
@@ -91,11 +91,17 @@ impl Config {
     /// and relies on you having the service account's token mounted,
     /// as well as having given the service account rbac access to do what you need.
     pub fn from_cluster_env() -> Result<Self> {
-        let cluster_url = incluster_config::kube_server().ok_or(ConfigError::MissingInClusterVariables {
-            hostenv: incluster_config::SERVICE_HOSTENV,
-            portenv: incluster_config::SERVICE_PORTENV,
-        })?;
-        let cluster_url = cluster_url.parse::<http::Uri>()?;
+
+        let cluster_url = if cfg!(feature = "rustls-tls") {
```
Comment (teozkr) [inline kube/src/config/mod.rs:95]: We still need to detect whether we're in-cluster somehow, so that we can fall back to kubeconfig as needed.

**Comment by clux** [comment]
Ohh, when __implementing a DNS server__ yeah. I get you. Yeah, I guess we need to expose a (probably non-default) way to decide what method to use when using incluster config.

File: kube/src/config/mod.rs (hunk 2 above)
Comment (clux) [reply kube/src/config/mod.rs:95]: This method is only dealing with incluster auth. The fallback happens above in `Config::infer`.

Comment (teozkr) [reply kube/src/config/mod.rs:95]: `Config::infer` just looks at whether `from_cluster_env` returned `Ok`.

**Comment by MikailBag** [comment]
I think kube-rs should just expose a way to completely override apiserver address (after all, it is perfectly valid for a Kubernetes pod to access apiserver from another cluster). And then user can read environment variables, some configs, etc.

File: kube/src/config/mod.rs (hunk 2 above)
Comment (clux) [reply kube/src/config/mod.rs:95]: And if it's not an `Ok`, we will fall back to a local kubeconfig. Are you worried that because we are looking at less evars that we might get an unintentional `Ok` and fail to fallback? We still have to find mounted certs and token files.

**Comment by clux** [comment]
> I think kube-rs should just expose a way to completely override apiserver address (after all, it is perfectly valid for a Kubernetes pod to access apiserver from another cluster). And then user can read environment variables, some configs, etc.

This is actually supported out of the box already:

```rust
let mut cfg = Config::from_cluster_env(); // or Config::infer
cfg.cluster_url = some_uri;
```

File: kube/src/config/mod.rs (hunk 2 above)
Comment (teozkr) [reply kube/src/config/mod.rs:95]: Oh, should be ok then.

**Comment by clux** [comment]
Going to merge this, tested this locally with controller-rs against a cluster running rustls for sanity so going to speculatively close the related issues. If it turns out to be positive, then we can discuss whether to swap out the default for non-rustls.
